#pragma once
#include <juce_audio_processors/juce_audio_processors.h>
#include "FeatureExtractor.h"
#include "ExpressionMapper.h"
#include "ModulationState.h"
#include "PitchToMidiConverter.h"
#include "SynthEngine.h"

/**
    Signal flow per block:
      input audio -> FeatureExtractor -> ExpressionMapper -> synthParams
                                       -> PitchToMidiConverter -> SynthEngine -> output audio

    Note triggering is audio-driven: PitchToMidiConverter turns detected
    pitch/amplitude into note-on/off events, so the synth is played by
    whatever's coming into the input rather than external MIDI. External
    MIDI input is still accepted by the host (acceptsMidi() is true) but
    is currently unused for note-triggering — see processBlock().

    Note detection behaviour is governed by an ArticulationProfile whose
    values come from live parameters, so it can be retuned per instrument
    without a rebuild.
*/
class ExpressionSynthProcessor : public juce::AudioProcessor,
                                  private juce::AudioProcessorValueTreeState::Listener,
                                  private juce::AsyncUpdater
{
public:
    ExpressionSynthProcessor();
    ~ExpressionSynthProcessor() override;

    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override {}
    void processBlock (juce::AudioBuffer<float>&, juce::MidiBuffer&) override;

    juce::AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override { return true; }

    const juce::String getName() const override { return "ExpressionSynth"; }
    bool acceptsMidi() const override { return true; }
    bool producesMidi() const override { return false; }
    double getTailLengthSeconds() const override { return 0.0; }

    int getNumPrograms() override { return 1; }
    int getCurrentProgram() override { return 0; }
    void setCurrentProgram (int) override {}
    const juce::String getProgramName (int) override { return {}; }
    void changeProgramName (int, const juce::String&) override {}

    void getStateInformation (juce::MemoryBlock& destData) override;
    void setStateInformation (const void* data, int sizeInBytes) override;

    juce::AudioProcessorValueTreeState& getParams() { return apvts; }

    // Configure routes here for now; move to a persisted/UI-editable
    // structure once the mapping UI exists.
    void setupDefaultRoutes();

    // --- Diagnostic accessors, read by the editor ---
    // First-test debugging matters unusually much here: builds go through
    // cloud CI, so "nothing is triggering and I can't tell why" would
    // otherwise cost a full rebuild cycle to investigate. These let the
    // UI show what the analyser is actually seeing, live.
    FeatureExtractor::Features getFeaturesForDisplay() const { return featureExtractor.getLatestFeatures(); }
    int getActiveNoteForDisplay() const { return pitchToMidi.getCurrentNote(); }
    juce::String getActiveProfileName() const { return pitchToMidi.getProfile().name; }

private:
    void parameterChanged (const juce::String& paramID, float newValue) override;

    // Rebuilds the converter's profile from current parameter values.
    void refreshArticulationProfile();

    // Applying a preset writes to host-visible parameters, which must
    // not happen on the audio thread. parameterChanged() can be called
    // from either thread, so it schedules this instead.
    void handleAsyncUpdate() override;

    juce::AudioProcessorValueTreeState apvts;

    FeatureExtractor featureExtractor;
    ExpressionMapper expressionMapper;
    PitchToMidiConverter pitchToMidi;
    SynthEngine synthEngine;

    // Scratch buffer for the mono-summed input fed to FeatureExtractor,
    // kept separate from the audio buffer that becomes synth output.
    juce::AudioBuffer<float> analysisBuffer;

    // Notes generated by pitchToMidi each block — separate from the
    // host's incoming MidiBuffer since note-triggering source has
    // switched from external MIDI to audio-derived.
    juce::MidiBuffer generatedMidi;

    // Smooths cents-deviation pitch expression (vibrato/bend on top of
    // the discrete note pitchToMidi selects) to avoid zipper noise.
    juce::SmoothedValue<float> pitchBendSmoother;

    // Live modulation produced by analysis, consumed by the synth.
    // Deliberately separate from APVTS — see ModulationState.h.
    ModulationState modulation;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (ExpressionSynthProcessor)
};
